### ISSUE TITLE
Apply APP2 to mouselight data

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#118]
APP2 is a popular neuron reconstruction algorithm and is available as a plug-in to Vaa3d. My main (open-ended) questions are:
-Can we apply Vaa3d plugins to our data?
-How well does APP2 work on our data?

The paper is [here](https://pubmed.ncbi.nlm.nih.gov/23603332/)

**Comment by fxu10** [comment]
I read through the APP2 paper and I'm interested in trying this algorithm on the Mouselight data. My concern is the GWDT soma labeling in a multi-neuron setting, since the algorithm is single-neuron and the selection is based on the assumption of only 1 soma being present in the image. I'm also unsure about how the path tracing will behave, I would imagine we would be able to discern between foreground and background and trace bright regions, but would be unable to label different neurons. We may need to do somethings manually like specifying the soma coordinates. Another concern is performance, which may be slow on our very high resolution images. But otherwise, the results presented in the paper seem very promising for an automatic (or in our case potentially semi-automatic) algorithm.

**Comment by tathey1** [comment]
partially addressed [here](https://github.com/neurodata/brainlit/pull/179)

**Comment by tathey1** [comment]
done [here](https://github.com/neurodata/brainlit/tree/develop/experiments/vaa3d_app2)
