### ISSUE TITLE
Add support for GeometricGraph in `brainlit.utils.swc.df_to_graph`

### ISSUE THREAD

**Issue by JacopoTeneggi** [neurodata/brainlit#164]
https://github.com/neurodata/brainlit/blob/a117ac52efec2224a4311c9167b33d46d90b3f05/brainlit/utils/swc.py#L313-L346

@tathey1 @bvarjavand should we extend this method to support `GeometricGraph` -- the class that we are importing with Chih-Ting's Sprint1? Fitting a neuron from S3 could then look something like

```python
s3_path = "s3://open-neurodata/brainlit/brain1_segments"
seg_id = 120
mip = 0
df_neuron = read_s3(s3_path, seg_id, mip)
g_neuron = df_to_graph(df_neuron, geometric-graph=True) # variant with flag to export in GeometricGraph type
spline_tree = g_neuron.fit_spline_tree_invariant()
```

**Comment by tathey1** [comment]
I believe this method is only used in order to view traces in napari. To this end, it immediately precedes `graph_to_paths`. The only discrepency in these graphs vs Geometric Graphs is if they're directed/undirected. Any directed graph can be converted to undirected with [this method](https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.to_undirected.html), and since GeometricGraphs have a root, we could convert undirected to directed with the help of [this method](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.edgedfs.edge_dfs.html#networkx.algorithms.traversal.edgedfs.edge_dfs) using root as the source. Are there any downsides to replacing df_to_graph and graph_to_paths with GeometricGraph versions? I'm leaning towards this option.

**Comment by JacopoTeneggi** [comment]
https://github.com/neurodata/brainlit/blob/731c5f45692dab63ab39ffb74feddd7ea539f48d/brainlit/utils/swc.py#L413-L422

This part of `graph_to_paths` is exactly what we do at the beginning of `fit_spline_tree_invariant` to identify the main branch and the collateral branches. What do you think about using `fit_spline_tree_invariant` to identify the branches so that we do not have duplicate code?

**Comment by tathey1** [comment]
Yes definitely don't want to have duplicate code. But I'm thinking the best option might be to have swc_to_graph just return a GeometricGraph, then this function could call GeometricGraph functions.

Also, we may want to split up  fit_spline_tree_invariant into two components: the splitting component, and the spline fitting component. What do you think?

**Comment by JacopoTeneggi** [comment]
After discussion with @tathey1 , the scope of this Issue has been restricted to fixing compatibility issues between `swc.read_s3` and the `GeometricGraph` class.

The fix includes:

-  remove the voxel unit approximation in `read_s3`
-  include a `init_from_df` private method in `GeometricGraph`
-  leave `session.py`, `tube_seg.py` as is (more accurate reformatting of these scripts will be necessary)
-  fix `session.get_segments` such that the paths are computed from the voxel unit dataframe
