### ISSUE TITLE
combined landmark and intensity registration and SyN

### ISSUE THREAD

**Issue by anorak94** [neurodata/brainlit#213]
Hey thanks for the wonderful package. Its nice to have a purely pythonic implementation of LDDMM. It would be nice to be able to do both landmark and intensity based registration in LDDMM at the same time. Also implementing SyN along with LDDMM. I am working on it. Would it be possible to add these extra modules and packages to brainlit registration module. I would be happy to contribute code to it as I think its a great initiative as there are not many pythonic implementations of these algorithms online.

https://brainevo.sitehost.iu.edu/publications/avants-chimp-human-morph.pdf 

this paper by avants shows how it might be done

**Comment by tathey1** [comment]
Hey @anorak94 , thanks for reaching out. We always want to support any contributions to our package. However to be honest, our registration submodule is not used heavily and may be dysfunctional. So, you may want to consider contributing to `scikit-image` instead (see our LDDMM PR [here](https://github.com/scikit-image/scikit-image/pull/5323)). I'm telling you this because I would want your contributions to be as impactful as possible! Let us know what you decide.

**Comment by tathey1** [comment]
My understanding is that [this](https://github.com/neurodata/CloudReg) is the go-to place for cloudreg code.
