### ISSUE TITLE
Upload 2018-08-01 brain (~14TB) to S3

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#59]
Parallelizing the upload of the higher resolutions has failed thus far.

**Comment by bvarjavand** [comment]
I will try to provide as much information as possible about the errors.  
Currently, running the upload for low-resolution images succeeds by `ssh`-ing into the CIS server (where the data is located, <user>@foo.cis.jhu.edu), then a compute server (such as `io49`).

In order to run code on this server, I recommend creating a conda environment using python3.7, cloning the brainlit repo, and running `pip install -e .` in the brainlit root directory.

The command to be run in question is `python brainlit/brainlit/utils/upload_to_neuroglancer.py --chosen-res i s3://mouse-light-viz/precomputed_volumes/brain1 /cis/local/jacs/data/jacsstorage/samples/2018-08-01/` where `i` is any resolution between 0 (highest) and 6 (lowest).

I include screenshots of some output when currently running the upload on resolution 2.

<img width="646" alt="Screen Shot 2020-07-21 at 8 50 42 AM" src="https://user-images.githubusercontent.com/8294669/89073102-b06b4d80-d32e-11ea-9e0a-6709f59bdc3c.png">

![Screen Shot 2020-07-21 at 2 29 02 PM](https://user-images.githubusercontent.com/8294669/89073118-bb25e280-d32e-11ea-8dbc-d2376042298a.png)

**Comment by bvarjavand** [comment]
Revised upload script still has the `UserWarning: A worker stopped [..]` warning.

**Comment by bvarjavand** [comment]
Done, data can be viewed [here](shorturl.at/aioxF). Issue not closed yet until validated and `brain1_2` dir replaces `brain1`

**Comment by bvarjavand** [comment]
`brain1_2` chunk size is too large, so `brain1` reuploaded using branch https://github.com/neurodata/brainlit/tree/old-upload . Workflow looked like 
 - ssh into the cis servers that contain the data (io49)
 - clone repo and cd into it
 - switch to old-upload branch
 - pip install -e .
 - cd ..
 - run upload

Running the upload looked like this:
<img width="1480" alt="Screen Shot 2020-08-10 at 1 03 45 PM" src="https://user-images.githubusercontent.com/8294669/89827989-42344100-db0d-11ea-88c0-c77abf342624.png">
