### ISSUE TITLE
incorporate prerna's soma detection code into brainlit

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#93]
Can use the 180 somas in brain1 as training data

**Comment by jovo** [comment]
please link to prerna's code here and/or create a branch that includes it @bvarjavand

**Comment by tathey1** [comment]
> please link to prerna's code here and/or create a branch that includes it @bvarjavand

https://github.com/prernasingh11/CLARITY

**Comment by johnduva** [comment]
**w.r.t. Cell_extractor4_22.ipynb:**
1. it will be interesting to see how transferable this is to two photon (en vivo) data given that its written for histology images
2. what is the purpose of extracting so much non-cell data? what happens if there is another cell within that space?
3. cell sizes range from two voxels to ten voxels. how do we currently confirm that (what we think are) large cells are not multiple overlapping ones, or artifacts of other sources? is there an existing strategy for human annotation to confirm cell bodies?

**w.r.t. M1 training and testing:**
1. cells in different parts of the brain have varying morphology. how well do we expect a machine trained on particular regions of the brain to generalize to others?
2. i’m not familiar with the difference between ‘coarse validation’ and ‘cross validation’ so I will need to research the former

**Comment by tathey1** [comment]
addressed [here](https://github.com/neurodata/brainlit/pull/180)

**Comment by tathey1** [comment]
@johnduva - this issue was closed. Can you document here what still needs to be done to justify reopening this? Or would you rather make a new issue and this one remain closed?
